/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

import events.MenuEventHandler;
import events.SliderHandler;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.nio.file.Paths;
import java.util.ArrayList;
import javax.swing.JFileChooser;

import net.miginfocom.swing.MigLayout;

/**
 *
 * @author maciek
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    private String pathToFile;
    private final MigLayout layout;
    private MenuEventHandler event;
    private SliderHandler sliderEvent;
    private boolean isFileSelected = false;

    public void addMenuEvent(MenuEventHandler event) {
        this.event = event;
    }

    public void addSliderEvent(SliderHandler sliderEvent) {
        this.sliderEvent = sliderEvent;
    }

    public void enableSlider(boolean shouldWork) {
        jSlider1.setEnabled(shouldWork);
    }

    public String getFilePath() {
        return pathToFile;
    }

    public void setFilePath(String s) {
        this.pathToFile = s;
    }

    public void DisplayPath(String path) {
        FileNameDisplay.setText(path);
    }

    public String getFileNameFromPath(String fullPath) {
        return Paths.get(fullPath).getFileName().toString();
    }

    public Menu() {
        initComponents();
        OptionScrollPane.getViewport().setOpaque(false);
        layout = new MigLayout("wrap, fillx, insets 0", "[fill]", "[]2[]");
        OptionPanel.setLayout(layout);
        setOpaque(false);
        initMenuItems();
    }

    void setupItem(MenuItem item) {
        item.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                item.setOpaque(true);
                item.setBackground(item.getBackground().darker());
            }

            @Override
            public void mouseExited(MouseEvent e) {
                item.setOpaque(false);
                item.setBackground(item.getBackground().brighter());
            }

            @Override
            public void mouseClicked(MouseEvent e) {
                if (isFileSelected) {
                    event.selected(item.getId());
                }

            }
        });
        OptionPanel.add(item);
    }

    private ArrayList<MenuItem> menuItems = new ArrayList<>();

    void initMenuItems() {

        menuItems.add(new MenuItem("SOLVE"));
        menuItems.add(new MenuItem("CLEAR"));
        menuItems.add(new MenuItem("SET START"));
        menuItems.add(new MenuItem("SET FINISH"));
        menuItems.add(new MenuItem("EXPORT TO PNG"));

        for (int i = 0; i < menuItems.size(); i++) {
            MenuItem item = menuItems.get(i);
            item.setId(i); // Assign a unique ID to each menu item
            setupItem(item);
        }

    }

    public void enableButtons() {
        isFileSelected = true;
    }

    @Override
    protected void paintChildren(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g = new GradientPaint(0, 0, Color.cyan, 0, getHeight(), Color.darkGray);
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        g2.fillRect(getWidth() - 20, 0, getWidth(), getHeight());
        super.paintChildren(grphcs);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OptionScrollPane = new javax.swing.JScrollPane();
        OptionPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        SetFileButton = new javax.swing.JButton();
        FileNameDisplay = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(238, 600));

        OptionScrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        OptionScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        OptionScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        OptionScrollPane.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        OptionScrollPane.setMinimumSize(getPreferredSize());
        OptionScrollPane.setOpaque(false);

        OptionPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        OptionPanel.setOpaque(false);
        OptionPanel.setPreferredSize(new java.awt.Dimension(114, 42));

        javax.swing.GroupLayout OptionPanelLayout = new javax.swing.GroupLayout(OptionPanel);
        OptionPanel.setLayout(OptionPanelLayout);
        OptionPanelLayout.setHorizontalGroup(
            OptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
        );
        OptionPanelLayout.setVerticalGroup(
            OptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );

        OptionScrollPane.setViewportView(OptionPanel);

        SetFileButton.setFont(new java.awt.Font("AnonymicePro Nerd Font", 3, 14)); // NOI18N
        SetFileButton.setText("Choose file");
        SetFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetFileButtonActionPerformed(evt);
            }
        });

        FileNameDisplay.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 13)); // NOI18N
        FileNameDisplay.setForeground(new java.awt.Color(240, 240, 240));
        FileNameDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FileNameDisplay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        FileNameDisplay.setMaximumSize(new java.awt.Dimension(55, 120));
        FileNameDisplay.setMinimumSize(new java.awt.Dimension(55, 120));
        FileNameDisplay.setPreferredSize(new java.awt.Dimension(55, 120));

        jSlider1.setMaximum(1000);
        jSlider1.setMinimum(1);
        jSlider1.setValue(200);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("AnonymicePro Nerd Font", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Adjust animation speed");

        jButton1.setFont(new java.awt.Font("AnonymicePro Nerd Font", 3, 18)); // NOI18N
        jButton1.setText("Settings");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(FileNameDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1)
                            .addComponent(SetFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(jSeparator3)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(SetFileButton)
                .addGap(8, 8, 8)
                .addComponent(FileNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(OptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public String getPathToExport() {
        String dir = System.getProperty("user.dir");

        JFileChooser j = new JFileChooser(dir);

        // invoke the showsOpenDialog function to show the save dialog
        int r = j.showSaveDialog(null);

        // if the user selects a file
        if (r == JFileChooser.APPROVE_OPTION) {
            // set the label to the path of the selected file
            return (j.getSelectedFile().getPath());
        } // if the user cancelled the operation
        else {
            return null;
        }
    }

    public void selectFile(String path) {
        pathToFile = (path);
        event.selected(-1);
        enableButtons();
    }

    private void SetFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetFileButtonActionPerformed
        String dir = System.getProperty("user.dir");

        JFileChooser j = new JFileChooser(dir);

        // invoke the showsOpenDialog function to show the save dialog
        int r = j.showOpenDialog(null);

        // if the user selects a file
        if (r == JFileChooser.APPROVE_OPTION) {
            // set the label to the path of the selected file
            selectFile(j.getSelectedFile().getPath());
        } // if the user cancelled the operation
        else
                ;
        //do literally nothing

    }//GEN-LAST:event_SetFileButtonActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        sliderEvent.setValue(jSlider1.getValue());
    }//GEN-LAST:event_jSlider1StateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        event.selected(-10);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FileNameDisplay;
    private javax.swing.JPanel OptionPanel;
    private javax.swing.JScrollPane OptionScrollPane;
    private javax.swing.JButton SetFileButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
